project_id = "uyrcxfypdzasdminxizq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.evolution-webhook]
    verify_jwt = false
  [functions.export-storage]
    verify_jwt = false
  [functions.google-forms-webhook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
