export interface InstrucaoTrabalho {
  id: string;
  popCodigo: string;
  titulo: string;
  objetivo: string;
  materiais: string[];
  epis: string[];
  passos: string[];
  criteriosAceitacao: string[];
  frequencia: string;
  registroVinculado?: string;
}

export const INSTRUCOES_TRABALHO: InstrucaoTrabalho[] = [
  // ═══════════════════════════════════════════
  // POP-01 — Qualificação de Fornecedores
  // ═══════════════════════════════════════════
  {
    id: "IT-01-01",
    popCodigo: "POP-01",
    titulo: "Avaliação e Qualificação Inicial de Fornecedor",
    objetivo: "Avaliar e qualificar novos fornecedores de matérias-primas, verificando documentação, registros MAPA/SIPEAGRO e capacidade de fornecimento.",
    materiais: ["Formulário de avaliação de fornecedores", "Acesso ao sistema SIPEAGRO", "Check-list de documentação obrigatória"],
    epis: [],
    passos: [
      "Solicitar ao fornecedor os documentos: CNPJ, Alvará de funcionamento, Registro MAPA, Registro SIPEAGRO dos produtos e Certificado de análise recente.",
      "Acessar o SIPEAGRO e verificar a validade do registro do estabelecimento e dos produtos fornecidos.",
      "Preencher o formulário de avaliação atribuindo nota (0 a 10) para: documentação, histórico de qualidade, atendimento e logística.",
      "Se a nota média for ≥ 7, aprovar o fornecedor. Caso contrário, registrar como 'aprovado com restrições' ou 'reprovado'.",
      "Cadastrar o fornecedor aprovado no sistema com todos os dados e documentos.",
      "Programar a próxima reavaliação (anual para aprovados, semestral para aprovados com restrições).",
    ],
    criteriosAceitacao: [
      "Registro SIPEAGRO válido e ativo",
      "Nota média ≥ 7 na avaliação",
      "Certificado de análise com resultados dentro dos limites especificados",
      "Documentação completa e vigente",
    ],
    frequencia: "A cada novo fornecedor e reavaliação anual",
    registroVinculado: "PL POP 1.1 — Avaliação de Fornecedores",
  },
  {
    id: "IT-01-02",
    popCodigo: "POP-01",
    titulo: "Inspeção de Recebimento de Matéria-Prima a Granel",
    objetivo: "Inspecionar e liberar matérias-primas a granel (milho, farelo de soja, etc.) no ato do recebimento.",
    materiais: ["Medidor de umidade (determinador rápido)", "Peneira granulométrica", "Calador/sonda de amostragem", "Formulário PL POP 1.3"],
    epis: ["Máscara PFF2", "Luvas", "Óculos de proteção"],
    passos: [
      "Verificar a nota fiscal e conferir com o pedido de compra (produto, quantidade, lote).",
      "Realizar amostragem representativa com calador em pelo menos 3 pontos da carga.",
      "Medir a umidade com determinador rápido — limite máximo: 14% para grãos.",
      "Avaliar aspecto visual: cor, odor, presença de insetos ou materiais estranhos.",
      "Registrar temperatura da carga (se aplicável).",
      "Se aprovada, autorizar o descarregamento no silo ou local indicado. Identificar com lote interno.",
      "Se reprovada, impedir o descarregamento, registrar a NC e comunicar o fornecedor.",
      "Reter amostra de contraprova (mín. 500g) identificada e armazenar por 6 meses.",
    ],
    criteriosAceitacao: [
      "Umidade ≤ 14%",
      "Ausência de insetos vivos",
      "Odor característico, sem sinais de fermentação ou mofo",
      "Temperatura da carga ≤ 40°C",
      "Nota fiscal conforme o pedido",
    ],
    frequencia: "A cada recebimento",
    registroVinculado: "PL POP 1.3 — Recebimento de Grãos",
  },
  {
    id: "IT-01-03",
    popCodigo: "POP-01",
    titulo: "Inspeção de Recebimento de Matéria-Prima Ensacada",
    objetivo: "Inspecionar matérias-primas ensacadas (premixes, aditivos, minerais) no recebimento.",
    materiais: ["Formulário PL POP 1.6", "Balança de conferência", "Etiquetas de identificação"],
    epis: ["Luvas", "Máscara PFF2"],
    passos: [
      "Conferir nota fiscal: produto, lote, quantidade, fabricação e validade.",
      "Inspecionar embalagens: integridade, ausência de rasgos, umidade ou contaminação.",
      "Verificar a presença de rótulo legível com todas as informações obrigatórias.",
      "Conferir peso de pelo menos 5% dos sacos aleatoriamente.",
      "Verificar o Certificado de Análise do lote.",
      "Armazenar na área de insumos sobre estrados, afastados 50 cm das paredes.",
      "Identificar com placa: nome do produto, fornecedor, lote, data de chegada, fabricação e validade.",
      "Registrar no formulário e reter amostra de contraprova quando aplicável.",
    ],
    criteriosAceitacao: [
      "Embalagens íntegras e lacradas",
      "Rótulo legível e completo",
      "Peso dentro da tolerância (±2%)",
      "Certificado de análise conforme",
      "Produto dentro do prazo de validade",
    ],
    frequencia: "A cada recebimento",
    registroVinculado: "PL POP 1.6 — Recebimento de Ensacados",
  },

  // ═══════════════════════════════════════════
  // POP-02 — Limpeza de Instalações e Equipamentos
  // ═══════════════════════════════════════════
  {
    id: "IT-02-01",
    popCodigo: "POP-02",
    titulo: "Limpeza a Seco de Áreas de Produção",
    objetivo: "Remover resíduos de produção por varrição ou aspiração sem uso de água, conforme IN 15/2009.",
    materiais: ["Vassoura industrial", "Pá coletora", "Aspirador industrial", "Soprador de folhas (áreas externas)"],
    epis: ["Máscara PFF2", "Óculos de proteção", "Luvas", "Protetor auricular"],
    passos: [
      "Desligar os equipamentos e aguardar parada total antes de iniciar.",
      "Varrer o piso da área de produção, direcionando os resíduos para a área de coleta.",
      "Utilizar aspirador industrial nos cantos, frestas e sob equipamentos.",
      "Limpar superfícies dos equipamentos (mesas, plataformas) com pano seco ou escova.",
      "Recolher os resíduos e destinar conforme classificação (orgânico/reciclável).",
      "Verificar visualmente a ausência de acúmulo de pó e partículas.",
      "Registrar na planilha de limpeza informando o tipo: 'Limpeza Seca'.",
    ],
    criteriosAceitacao: [
      "Piso visualmente limpo, sem acúmulo de resíduos",
      "Equipamentos sem incrustações visíveis",
      "Ausência de poeira em cantos e frestas",
    ],
    frequencia: "Diária (a cada turno) e após cada troca de produto",
    registroVinculado: "PL POP 2.1 — Registro de Limpeza",
  },
  {
    id: "IT-02-02",
    popCodigo: "POP-02",
    titulo: "Limpeza Úmida e Sanitização",
    objetivo: "Realizar lavagem e sanitização de áreas que permitem uso de água, como vestiários, refeitórios e áreas de apoio.",
    materiais: ["Detergente neutro", "Sanitizante (hipoclorito de sódio 200 ppm)", "Rodo", "Balde", "Pano de limpeza", "Borrifador"],
    epis: ["Luvas de borracha", "Botas de borracha", "Óculos de proteção", "Avental impermeável"],
    passos: [
      "Remover resíduos sólidos com varrição prévia.",
      "Preparar solução detergente conforme diluição do fabricante.",
      "Aplicar a solução detergente com pano ou rodo, esfregando as superfícies.",
      "Enxaguar com água limpa até remoção completa do detergente.",
      "Preparar solução sanitizante (hipoclorito 200 ppm) e aplicar por contato mínimo de 15 minutos.",
      "Não enxaguar após sanitização (ação residual).",
      "Secar pisos com rodo. Equipamentos: deixar secar ao ar.",
      "Registrar na planilha como 'Limpeza Úmida + Sanitização'.",
    ],
    criteriosAceitacao: [
      "Superfícies limpas e sem resíduo de produto ou detergente",
      "Odor de sanitizante residual perceptível",
      "Ausência de poças de água remanescentes no piso",
      "Tempo de contato do sanitizante ≥ 15 min",
    ],
    frequencia: "Semanal (áreas de apoio) / Conforme cronograma para produção",
    registroVinculado: "PL POP 2.1 — Registro de Limpeza",
  },
  {
    id: "IT-02-03",
    popCodigo: "POP-02",
    titulo: "Limpeza de Silos e Transportadores",
    objetivo: "Higienizar silos de armazenamento e linhas de transporte (roscas, elevadores) para evitar arraste de medicamentos e aditivos (IN 15/2009).",
    materiais: ["Aspirador industrial de alta potência", "Escova de cerdas longas", "Soprador", "Lanterna de inspeção", "Etiquetas de identificação"],
    epis: ["Máscara PFF2", "Capacete", "Cinto de segurança tipo paraquedista (silos)", "Luvas", "Protetor auricular"],
    passos: [
      "Esvaziar completamente o silo ou transportador. Confirmar ausência de produto residual.",
      "Verificar se o equipamento está desligado e bloqueado (LOTO).",
      "Aspirar resíduos internos do silo com aspirador industrial.",
      "Escovar paredes internas para remoção de incrustações.",
      "Inspecionar com lanterna: verificar ausência de resíduos aderidos, presença de insetos ou mofo.",
      "Nos transportadores (roscas/elevadores): abrir as tampas de inspeção, aspirar e escovar.",
      "Registrar na planilha específica de silos e transportadores.",
      "Identificar o silo/transportador como 'LIMPO — Liberado para uso' com data e responsável.",
    ],
    criteriosAceitacao: [
      "Interior do silo visualmente limpo e sem incrustações",
      "Ausência de resíduos de produto anterior no transportador",
      "Ausência de insetos ou sinais de infestação",
      "Etiqueta de liberação fixada e atualizada",
    ],
    frequencia: "Mensal ou a cada troca de produto armazenado",
    registroVinculado: "PL POP 2.3 — Limpeza de Silos e Transportadores",
  },

  // ═══════════════════════════════════════════
  // POP-03 — Higiene e Saúde dos Colaboradores
  // ═══════════════════════════════════════════
  {
    id: "IT-03-01",
    popCodigo: "POP-03",
    titulo: "Higiene Pessoal na Entrada da Fábrica",
    objetivo: "Garantir que todos os colaboradores e visitantes cumpram os procedimentos de higiene antes de acessar as áreas de produção.",
    materiais: ["Sabonete líquido bactericida", "Álcool gel 70%", "Papel toalha", "Pedilúvio com solução sanitizante", "Instruções ilustradas fixadas"],
    epis: ["Uniforme completo da empresa", "Touca/boné", "Calçado fechado de segurança"],
    passos: [
      "Trocar roupas pessoais pelo uniforme no vestiário antes de acessar a produção.",
      "Lavar as mãos com sabonete bactericida por pelo menos 20 segundos.",
      "Secar as mãos com papel toalha descartável.",
      "Aplicar álcool gel 70% nas mãos e antebraços.",
      "Passar pelo pedilúvio na entrada da área produtiva.",
      "Verificar que não porta adornos (relógio, pulseiras, anéis, brincos).",
      "Conferir integridade do uniforme e uso correto de touca/boné.",
    ],
    criteriosAceitacao: [
      "Mãos lavadas e sanitizadas",
      "Uniforme limpo e íntegro",
      "Ausência de adornos pessoais",
      "Passagem obrigatória pelo pedilúvio",
    ],
    frequencia: "A cada entrada na área produtiva",
    registroVinculado: "PL POP 3.1 — Higiene Pessoal",
  },
  {
    id: "IT-03-02",
    popCodigo: "POP-03",
    titulo: "Controle de Atestados de Saúde Ocupacional (ASO)",
    objetivo: "Gerenciar a validade dos exames médicos (ASO) de todos os colaboradores conforme NR-7.",
    materiais: ["Planilha de controle de ASOs", "Agenda de exames periódicos"],
    epis: [],
    passos: [
      "Cadastrar todos os colaboradores no controle de ASOs com data do último exame e validade.",
      "Monitorar mensalmente os vencimentos dos ASOs.",
      "Agendar exames periódicos com 30 dias de antecedência do vencimento.",
      "Após realização do exame, atualizar a planilha com a nova data de validade.",
      "Arquivar cópia do ASO na pasta do colaborador.",
      "Colaboradores com ASO vencido devem ser afastados das atividades até regularização.",
    ],
    criteriosAceitacao: [
      "100% dos colaboradores com ASO válido",
      "Agendamentos realizados com antecedência mínima de 30 dias",
      "ASOs arquivados e disponíveis para fiscalização",
    ],
    frequencia: "Monitoramento mensal / Exames conforme periodicidade NR-7",
    registroVinculado: "PL POP 3.2 — Controle de Saúde dos Manipuladores",
  },

  // ═══════════════════════════════════════════
  // POP-04 — Potabilidade da Água
  // ═══════════════════════════════════════════
  {
    id: "IT-04-01",
    popCodigo: "POP-04",
    titulo: "Coleta de Amostras de Água para Análise",
    objetivo: "Coletar amostras de água em pontos estratégicos para análise laboratorial de potabilidade.",
    materiais: ["Frascos estéreis para coleta", "Etiquetas de identificação", "Caixa térmica com gelo", "Kit de cloro residual (DPD)"],
    epis: ["Luvas estéreis", "Jaleco"],
    passos: [
      "Identificar os pontos de coleta conforme mapa da rede hidráulica (mínimo: entrada, reservatório, ponto de uso).",
      "Flambar ou sanitizar a torneira do ponto de coleta.",
      "Deixar a água correr por 2-3 minutos antes da coleta.",
      "Coletar a amostra no frasco estéril sem tocar na parte interna.",
      "Medir o cloro residual no ponto com kit DPD — resultado esperado: 0,2 a 2,0 mg/L.",
      "Identificar o frasco: ponto, data, hora, responsável pela coleta.",
      "Acondicionar em caixa térmica com gelo e enviar ao laboratório em até 24 horas.",
      "Registrar a coleta na planilha de potabilidade.",
    ],
    criteriosAceitacao: [
      "Cloro residual entre 0,2 e 2,0 mg/L",
      "Amostra enviada ao laboratório em ≤ 24h",
      "Frasco estéril e corretamente identificado",
    ],
    frequencia: "Mensal (pontos de uso) / Semestral (análise completa)",
    registroVinculado: "PL POP 4.1 — Controle de Potabilidade da Água",
  },
  {
    id: "IT-04-02",
    popCodigo: "POP-04",
    titulo: "Higienização de Reservatórios de Água",
    objetivo: "Limpar e sanitizar reservatórios (caixas d'água) conforme periodicidade da IN 04/2007.",
    materiais: ["Escova de cerdas macias", "Hipoclorito de sódio (200 ppm)", "Balde", "Mangueira", "Etiqueta de registro"],
    epis: ["Botas de borracha", "Luvas de borracha", "Máscara", "Óculos de proteção"],
    passos: [
      "Fechar o registro de entrada e esvaziar o reservatório.",
      "Remover resíduos sólidos do fundo com balde.",
      "Escovar paredes e fundo com escova de cerdas macias (sem uso de detergente).",
      "Enxaguar com água limpa até remoção total dos resíduos.",
      "Preparar solução de hipoclorito de sódio 200 ppm e aplicar nas paredes internas.",
      "Deixar agir por 30 minutos com o reservatório fechado.",
      "Enxaguar e preencher o reservatório.",
      "Medir cloro residual na saída — deve estar entre 0,2 e 2,0 mg/L.",
      "Fixar etiqueta no reservatório: data da limpeza, responsável, próxima limpeza.",
    ],
    criteriosAceitacao: [
      "Reservatório visualmente limpo sem resíduos ou biofilme",
      "Cloro residual na saída entre 0,2 e 2,0 mg/L",
      "Etiqueta de controle fixada e atualizada",
    ],
    frequencia: "Semestral",
    registroVinculado: "PL POP 4.2 — Higienização de Reservatórios",
  },

  // ═══════════════════════════════════════════
  // POP-05 — Prevenção de Contaminação Cruzada
  // ═══════════════════════════════════════════
  {
    id: "IT-05-01",
    popCodigo: "POP-05",
    titulo: "Sequenciamento de Produção e Flushing",
    objetivo: "Definir a ordem de fabricação e executar o flushing entre fórmulas para prevenir contaminação cruzada por medicamentos e aditivos (IN 15/2009).",
    materiais: ["Programação de produção do dia", "Matriz de sensibilidade", "Material inerte para flushing (milho moído, calcário)", "Etiquetas de identificação"],
    epis: ["Máscara PFF2", "Luvas"],
    passos: [
      "Consultar a programação de produção e a matriz de sensibilidade.",
      "Ordenar a produção do produto de MENOR risco para o de MAIOR risco (ex: sem medicamento → com medicamento).",
      "Antes da troca de fórmula com medicamento/aditivo, executar flushing com material inerte.",
      "Quantidade de flushing: mínimo 1% da capacidade do misturador ou conforme validação.",
      "Destinar o material de flushing conforme procedimento (reprocesso ou descarte).",
      "Registrar no sistema: produto anterior, produto seguinte, volume de flushing, destino do material.",
      "Quando a sequência envolve rações para ruminantes após não-ruminantes com POA: flushing obrigatório com volume validado.",
    ],
    criteriosAceitacao: [
      "Sequência respeitada conforme matriz de sensibilidade",
      "Flushing executado e registrado antes de troca de fórmula crítica",
      "Material de flushing destinado corretamente",
      "Teste de carry-over conforme quando aplicável",
    ],
    frequencia: "A cada troca de fórmula com risco de contaminação",
    registroVinculado: "PL POP 5.1 — Sequenciamento e Flushing",
  },
  {
    id: "IT-05-02",
    popCodigo: "POP-05",
    titulo: "Teste de Carry-Over (Arraste)",
    objetivo: "Verificar a eficácia do flushing e da limpeza de linha por meio de análise laboratorial de arraste de medicamentos.",
    materiais: ["Frascos de coleta identificados", "Formulário de coleta de carry-over", "Caixa térmica"],
    epis: ["Luvas", "Máscara PFF2"],
    passos: [
      "Após o flushing, coletar amostra do PRIMEIRO lote do produto subsequente (amostra pós-flushing).",
      "Coletar também amostra do material de flushing.",
      "Identificar as amostras: data, lote anterior, lote atual, ponto de coleta.",
      "Enviar ao laboratório para análise do princípio ativo do medicamento anterior.",
      "Resultado esperado: concentração do princípio ativo < 1% do nível terapêutico.",
      "Se resultado não conforme: aumentar volume de flushing, repetir limpeza e refazer o teste.",
      "Registrar resultados na planilha de carry-over e arquivar o laudo.",
    ],
    criteriosAceitacao: [
      "Arraste < 1% do nível terapêutico do medicamento",
      "Laudo laboratorial arquivado",
      "Ação corretiva aplicada em caso de não conformidade",
    ],
    frequencia: "Trimestral (validação) ou quando houver mudança no processo",
    registroVinculado: "PL POP 5.2 — Teste de Carry-Over",
  },

  // ═══════════════════════════════════════════
  // POP-06 — Manutenção e Calibração
  // ═══════════════════════════════════════════
  {
    id: "IT-06-01",
    popCodigo: "POP-06",
    titulo: "Manutenção Preventiva de Equipamentos Críticos",
    objetivo: "Executar manutenção preventiva em moinhos, misturadores e peletizadoras conforme cronograma, evitando paradas não programadas e contaminação.",
    materiais: ["Ferramentas de manutenção", "Peças de reposição conforme estoque", "Lubrificantes de grau alimentício", "Formulário de manutenção"],
    epis: ["Luvas de vaqueta", "Óculos de proteção", "Protetor auricular", "Capacete"],
    passos: [
      "Consultar o cronograma de manutenção preventiva do mês.",
      "Desligar e bloquear o equipamento (LOTO) antes de iniciar.",
      "Inspecionar o equipamento: desgaste de peças, folgas, vibração anormal, vazamentos.",
      "Substituir peças conforme plano (martelos, telas, correias, rolamentos).",
      "Lubrificar pontos indicados com lubrificante de grau alimentício.",
      "Realizar teste de funcionamento em vazio após a manutenção.",
      "Registrar no formulário: equipamento, peças trocadas, custo, responsável, próxima manutenção.",
      "Limpar a área ao redor do equipamento após o serviço.",
    ],
    criteriosAceitacao: [
      "Equipamento funcionando sem vibração ou ruído anormal",
      "Peças substituídas conforme vida útil ou condição",
      "Lubrificação com produto de grau alimentício",
      "Registro completo com data da próxima manutenção",
    ],
    frequencia: "Conforme cronograma (mensal a trimestral por equipamento)",
    registroVinculado: "PL POP 6.1 — Manutenção Preventiva",
  },
  {
    id: "IT-06-02",
    popCodigo: "POP-06",
    titulo: "Verificação Intermediária de Balanças",
    objetivo: "Realizar verificação intermediária das balanças entre calibrações para garantir a precisão das pesagens.",
    materiais: ["Pesos padrão certificados (1 kg, 5 kg, 10 kg, 25 kg)", "Formulário de verificação", "Calculadora"],
    epis: ["Luvas"],
    passos: [
      "Zerar/tarar a balança conforme manual do fabricante.",
      "Posicionar o peso padrão de menor valor no centro do prato.",
      "Registrar o valor indicado e calcular o erro: |valor indicado - valor nominal|.",
      "Repetir com pesos intermediários e no limite máximo da faixa de uso.",
      "Comparar os erros encontrados com a tolerância admissível (geralmente ±0,1% da carga).",
      "Se dentro da tolerância: registrar como CONFORME.",
      "Se fora da tolerância: interditar a balança, identificar como 'FORA DE USO' e solicitar calibração.",
    ],
    criteriosAceitacao: [
      "Erro ≤ tolerância admissível em todos os pontos verificados",
      "Balança limpa e nivelada",
      "Pesos padrão com certificado de calibração válido",
    ],
    frequencia: "Semanal ou conforme plano de calibração",
    registroVinculado: "PL POP 6.2 — Verificação de Balanças",
  },

  // ═══════════════════════════════════════════
  // POP-07 — Controle Integrado de Pragas
  // ═══════════════════════════════════════════
  {
    id: "IT-07-01",
    popCodigo: "POP-07",
    titulo: "Monitoramento de Armadilhas e Iscas",
    objetivo: "Inspecionar e registrar a situação das armadilhas e iscas do programa de controle integrado de pragas.",
    materiais: ["Mapa de localização das armadilhas", "Formulário de monitoramento", "Lanternas", "Luvas descartáveis"],
    epis: ["Luvas descartáveis", "Máscara"],
    passos: [
      "Obter o mapa atualizado com a localização e numeração de todas as armadilhas.",
      "Percorrer todos os pontos na ordem do mapa, iniciando pelo perímetro externo.",
      "Em cada armadilha: verificar integridade, presença de capturas e condição da isca.",
      "Registrar no formulário: número da armadilha, tipo, status (ativa/danificada), capturas.",
      "Substituir iscas consumidas ou danificadas.",
      "Repor armadilhas danificadas e registrar a substituição.",
      "Comunicar ao RT qualquer aumento significativo de capturas ou infestação.",
      "Ao final, atualizar o mapa se houve alteração de posição ou número de armadilhas.",
    ],
    criteriosAceitacao: [
      "100% das armadilhas inspecionadas conforme mapa",
      "Armadilhas danificadas substituídas no mesmo dia",
      "Registro completo de todas as inspeções",
      "Comunicação imediata ao RT em caso de infestação",
    ],
    frequencia: "Semanal (armadilhas internas) / Quinzenal (perímetro externo)",
    registroVinculado: "PL POP 7.1 — Monitoramento de Pragas",
  },
  {
    id: "IT-07-02",
    popCodigo: "POP-07",
    titulo: "Inspeção de Barreiras Físicas Contra Pragas",
    objetivo: "Verificar a integridade das barreiras físicas (telas, ralos, portas) que impedem a entrada de pragas.",
    materiais: ["Check-list de barreiras", "Fita métrica", "Ferramenta para pequenos reparos"],
    epis: ["Luvas"],
    passos: [
      "Inspecionar todas as telas nas janelas e aberturas — verificar ausência de rasgos ou furos.",
      "Verificar o fechamento automático de portas de acesso às áreas de produção.",
      "Inspecionar as borrachas de vedação (rodapé) nas portas — verificar desgaste.",
      "Verificar ralos com tampa anti-praga: funcionamento e estado de conservação.",
      "Inspecionar áreas externas: vegetação próxima às paredes (manter mín. 1m de distância).",
      "Registrar no check-list: item, situação (conforme/não conforme), ação necessária.",
      "Para não conformidades: solicitar reparo ao setor de manutenção com prazo.",
    ],
    criteriosAceitacao: [
      "Telas íntegras e sem aberturas > 2mm",
      "Portas com fechamento automático funcionando",
      "Borrachas de vedação em bom estado",
      "Ralos com tampa anti-praga funcional",
    ],
    frequencia: "Mensal",
    registroVinculado: "PL POP 7.2 — Barreiras Físicas",
  },

  // ═══════════════════════════════════════════
  // POP-08 — Controle de Resíduos e Efluentes
  // ═══════════════════════════════════════════
  {
    id: "IT-08-01",
    popCodigo: "POP-08",
    titulo: "Segregação e Coleta de Resíduos Sólidos",
    objetivo: "Classificar, segregar e destinar corretamente os resíduos sólidos gerados na fábrica.",
    materiais: ["Coletores identificados por cor/tipo", "Sacos plásticos apropriados", "Etiquetas de identificação", "Balança"],
    epis: ["Luvas de borracha", "Botas", "Máscara (se resíduos contaminados)"],
    passos: [
      "Identificar o tipo de resíduo: Classe I (perigoso), Classe IIA (não inerte), Classe IIB (inerte).",
      "Depositar no coletor correto conforme o código de cores do PGRS da empresa.",
      "Resíduos de medicamentos/aditivos: coletar em recipiente separado como Classe I.",
      "Ao final do turno: pesar os resíduos de cada categoria e registrar.",
      "Armazenar temporariamente em local coberto, protegido e identificado.",
      "Verificar se a empresa coletora possui licença ambiental válida.",
      "No momento da coleta: emitir manifesto de transporte de resíduos (MTR).",
      "Arquivar os manifestos por 5 anos.",
    ],
    criteriosAceitacao: [
      "Resíduos segregados corretamente por classe",
      "Pesagem diária registrada",
      "Armazenamento temporário em local adequado",
      "MTR emitido e arquivado a cada coleta",
    ],
    frequencia: "Diária (segregação) / Conforme contrato (coleta)",
    registroVinculado: "PL POP 8.1 — Controle de Resíduos",
  },
  {
    id: "IT-08-02",
    popCodigo: "POP-08",
    titulo: "Descarte de Produtos Não Conformes",
    objetivo: "Destinar corretamente produtos acabados ou matérias-primas que foram reprovados, vencidos ou recolhidos.",
    materiais: ["Formulário de descarte", "Etiquetas 'PRODUTO NÃO CONFORME'", "Câmera para evidências fotográficas"],
    epis: ["Luvas", "Máscara PFF2"],
    passos: [
      "Identificar o produto: nome, lote, quantidade, motivo do descarte.",
      "Segregar imediatamente em área de quarentena identificada.",
      "Fixar etiqueta 'PRODUTO NÃO CONFORME — AGUARDANDO DESCARTE'.",
      "Registrar no formulário de descarte com evidências fotográficas.",
      "Avaliar a destinação: reprocessamento, venda para reciclagem animal ou descarte definitivo.",
      "Se descarte definitivo: acionar empresa coletora licenciada.",
      "Registrar a rastreabilidade completa do descarte (MTR, NF, destino final).",
      "Comunicar ao RT e arquivar toda a documentação.",
    ],
    criteriosAceitacao: [
      "Produto segregado e identificado imediatamente",
      "Rastreabilidade completa do descarte documentada",
      "Autorização do RT antes do descarte definitivo",
      "Documentação arquivada por 5 anos",
    ],
    frequencia: "A cada ocorrência",
    registroVinculado: "PL POP 8.2 — Descarte de Produtos",
  },

  // ═══════════════════════════════════════════
  // POP-09 — Rastreabilidade, Armazenamento, Transporte e Recall
  // ═══════════════════════════════════════════
  {
    id: "IT-09-01",
    popCodigo: "POP-09",
    titulo: "Registro de Rastreabilidade Lote a Lote",
    objetivo: "Garantir a rastreabilidade completa desde as matérias-primas até o destino do produto acabado.",
    materiais: ["Sistema de rastreabilidade (digital ou formulário)", "Etiquetas de lote", "Notas fiscais"],
    epis: [],
    passos: [
      "Para cada ordem de produção: registrar o lote do produto acabado e a data de fabricação.",
      "Vincular ao lote do PA: todos os lotes de matérias-primas utilizadas na fórmula.",
      "Registrar o fornecedor e nota fiscal de cada MP.",
      "Após expedição: registrar o destino do lote (cliente, NF de saída, quantidade, data de venda).",
      "Para produtos com ingredientes de origem animal: registrar o tipo e origem específica.",
      "Verificar que a cadeia está completa: MP → Produção → PA → Cliente.",
      "Manter registros por no mínimo 5 anos.",
    ],
    criteriosAceitacao: [
      "100% dos lotes com rastreabilidade completa (montante e jusante)",
      "Tempo de recuperação de informações ≤ 4 horas",
      "Vínculo MP ↔ PA ↔ Cliente documentado",
    ],
    frequencia: "A cada lote produzido/expedido",
    registroVinculado: "PL POP 9.1 — Rastreabilidade",
  },
  {
    id: "IT-09-02",
    popCodigo: "POP-09",
    titulo: "Procedimento de Recall (Recolhimento)",
    objetivo: "Executar o recolhimento de produtos do mercado quando identificado risco à segurança alimentar.",
    materiais: ["Lista de contatos de clientes", "Notas fiscais de venda do lote", "Formulário de recall", "Veículo para recolhimento"],
    epis: [],
    passos: [
      "Identificar o motivo do recall: contaminação, desvio de qualidade, medicamento irregular.",
      "Definir os lotes afetados usando o sistema de rastreabilidade.",
      "Comunicar imediatamente ao SIF/MAPA local.",
      "Identificar todos os clientes que receberam os lotes afetados.",
      "Emitir comunicado formal aos clientes com instrução de retenção do produto.",
      "Iniciar o recolhimento físico dos produtos.",
      "Segregar os produtos recolhidos em área de quarentena identificada.",
      "Definir destinação final (descarte, reprocessamento) com aprovação do RT.",
      "Elaborar relatório final com: causa, lotes afetados, quantidade recolhida, destino e ações preventivas.",
      "Comunicar ao MAPA o encerramento do recall.",
    ],
    criteriosAceitacao: [
      "100% dos clientes afetados comunicados em ≤ 24h",
      "Recolhimento físico ≥ 80% da quantidade vendida",
      "Relatório final entregue ao MAPA",
      "Ação preventiva implementada",
    ],
    frequencia: "A cada ocorrência / Simulado anual",
    registroVinculado: "PL POP 9.2 — Recall / Recolhimento",
  },

  // ═══════════════════════════════════════════
  // POP-10 — PAC (Programa de Autocontrole)
  // ═══════════════════════════════════════════
  {
    id: "IT-10-01",
    popCodigo: "POP-10",
    titulo: "Auditoria Interna de Autocontrole",
    objetivo: "Executar auditoria interna dos programas de autocontrole (PAC) para verificar a efetividade dos controles implementados.",
    materiais: ["Checklist de auditoria (68 itens)", "Relatório de auditoria anterior", "Planilhas de registro dos POPs", "Câmera para evidências"],
    epis: ["Uniforme", "Touca", "Calçado fechado"],
    passos: [
      "Planejar a auditoria: definir data, escopo (quais POPs/áreas) e auditor (≠ responsável pela área).",
      "Revisar o relatório da auditoria anterior e verificar se as ações corretivas foram implementadas.",
      "Percorrer as áreas com o checklist, verificando evidências objetivas (registros, condições físicas).",
      "Entrevistar operadores sobre os procedimentos — verificar conhecimento prático.",
      "Para cada item: classificar como Conforme (C), Não Conforme (NC) ou Não Aplicável (NA).",
      "Fotografar não conformidades como evidência.",
      "Calcular o índice de conformidade geral: (C / (C+NC)) × 100%.",
      "Emitir relatório de auditoria com NCs identificadas, prazos e responsáveis.",
      "Abrir RNC (Registro de Não Conformidade) para cada NC encontrada.",
    ],
    criteriosAceitacao: [
      "Índice de conformidade ≥ 80% (meta: ≥ 90%)",
      "Todas as NCs com ação corretiva e prazo definido",
      "Relatório disponível para o SIF/MAPA",
      "Auditoria realizada por auditor independente da área",
    ],
    frequencia: "Mensal (parcial) / Trimestral (completa)",
    registroVinculado: "PL POP 10.1 — Auditoria Interna",
  },
  {
    id: "IT-10-02",
    popCodigo: "POP-10",
    titulo: "Análise Crítica dos Indicadores de Qualidade",
    objetivo: "Analisar criticamente os indicadores de desempenho dos programas de autocontrole para tomada de decisão.",
    materiais: ["Dashboard de indicadores", "Relatórios dos módulos", "Ata de reunião anterior"],
    epis: [],
    passos: [
      "Reunir os indicadores-chave: conformidade de auditorias, NCs abertas/fechadas, reclamações, desvios de produção.",
      "Verificar a tendência dos indicadores (melhora, estabilidade ou piora).",
      "Identificar causas-raiz de indicadores em queda.",
      "Definir ações de melhoria com responsáveis e prazos.",
      "Verificar a eficácia das ações definidas na reunião anterior.",
      "Registrar em ata de reunião de análise crítica.",
      "Comunicar resultados e decisões à equipe.",
    ],
    criteriosAceitacao: [
      "Reunião realizada com ata assinada pelo RT",
      "Indicadores revisados com tendência documentada",
      "Ações de melhoria definidas com prazos",
      "Verificação de eficácia das ações anteriores",
    ],
    frequencia: "Mensal",
    registroVinculado: "PL POP 10.2 — Análise Crítica",
  },
];