import { DOCUMENTOS_ATIVACAO_CHECKLIST } from "@/config/documentosAtivacaoChecklist";
import manualBpfDocAsset from "@/assets/modelos/manual_bpf.docx.asset.json";

export interface ManualBpfSection {
  id: string;
  numero: string;
  titulo: string;
  conteudo: string[];
  linkModelo?: string;
}

export const MANUAL_BPF_ASSET_URL = manualBpfDocAsset.url;

export const MANUAL_BPF_SECTIONS: ManualBpfSection[] = [
  {
    id: "identificacao",
    numero: "1",
    titulo: "Identificação da Empresa",
    conteudo: [
      "RAZÃO SOCIAL: (Preencher com a razão social da empresa)",
      "NOME FANTASIA: (Preencher com o nome fantasia)",
      "REGISTRO MAPA: SIF – XX – 000000-0",
      "ENDEREÇO: (Endereço completo)",
      "CIDADE: (Cidade - UF)",
      "CEP: 00000-000",
      "RESPONSÁVEL TÉCNICO: (Nome do RT)",
      "HORÁRIO DE FUNCIONAMENTO: (Informar horário de funcionamento)",
    ],
  },
  {
    id: "objetivo",
    numero: "2",
    titulo: "Objetivo",
    conteudo: [
      "O Manual de Boas Práticas de Fabricação tem como base a Instrução Normativa 04, de 13 de fevereiro de 2007 — Regulamentos Técnicos sobre as condições higiênico-sanitárias e de boas práticas de fabricação para estabelecimentos fabricantes de alimentos para animais.",
      "O objetivo é estabelecer diretrizes relativas à implementação e gestão das normas internas que regem as boas práticas de fabricação na unidade, assegurando que os requisitos essenciais sejam adequadamente seguidos e compreendidos.",
      "O manual descreve as operações realizadas na planta, englobando: higiene sanitária, higienização das instalações, equipamentos e utensílios, controle de pragas, controle da qualidade da água, controle dos hábitos higiênicos e saúde dos funcionários, garantia da rastreabilidade e qualidade do produto final, e prevenção da contaminação cruzada.",
    ],
  },
  {
    id: "aplicacao",
    numero: "3",
    titulo: "Aplicação",
    conteudo: [
      "Este manual aplica-se a todos os funcionários e setores envolvidos, direta ou indiretamente, com o processamento industrial de rações.",
    ],
  },
  {
    id: "definicoes",
    numero: "4",
    titulo: "Definições",
    conteudo: [
      "BOAS PRÁTICAS DE FABRICAÇÃO (BPF): Procedimentos higiênico-sanitários e operacionais aplicados em todo o fluxo de produção, desde a obtenção dos ingredientes até a distribuição do produto, com o objetivo de garantir a qualidade, conformidade e segurança dos produtos à alimentação animal.",
      "CONTAMINAÇÃO: Presença de substâncias ou agentes estranhos de origem biológica, química ou física que se considerem indesejáveis ao produto.",
      "CONTAMINAÇÃO CRUZADA: Contaminação de produtos destinados à alimentação animal com outro produto, durante o processo de produção ou contaminação gerada pelo contato indevido de ingredientes, insumos, superfícies, ambiente, pessoas ou produtos contaminados.",
      "CONTROLE DE QUALIDADE: Conjunto de procedimentos que envolvem programação, coordenação e execução com o objetivo de verificar e assegurar a conformidade da matéria-prima, do ingrediente, do rótulo, da embalagem e do produto acabado.",
      "DESINFECÇÃO / SANITIZAÇÃO: Operação de redução por método físico e/ou agente químico do número de microrganismos a um nível que não comprometa a inocuidade do alimento.",
      "EMBALAGEM PRIMÁRIA: Embalagem que mantém contato direto com o produto.",
      "HIGIENIZAÇÃO: Operação que compreende duas etapas: limpeza e desinfecção.",
      "LIMPEZA: Operação de remoção de substâncias minerais e orgânicas indesejáveis.",
      "LOTE: Quantidade de um produto elaborado em um ciclo de fabricação, cuja característica essencial é a homogeneidade.",
      "MATÉRIA-PRIMA / INGREDIENTE: Toda substância que se emprega na fabricação de alimentos para animais.",
      "POP — Procedimento Operacional Padrão: Procedimento escrito de forma objetiva que estabelece instruções sequenciais para a realização de operações rotineiras e específicas na produção.",
      "PRODUTO ACABADO: Produto que já passou por todas as etapas de produção.",
      "RASTREABILIDADE: Capacidade de detectar a origem e de seguir o rastro de um alimento, de uma substância ou objeto, ao longo de todas as etapas da produção, transformação e distribuição.",
    ],
  },
  {
    id: "instalacoes",
    numero: "5",
    titulo: "Descrição das Instalações e Fluxo de Produção",
    conteudo: [
      "Descrever nesta seção o layout físico da fábrica, incluindo: área de recepção de matérias-primas, áreas de estocagem (silos, armazéns), área de pesagem e mistura, área de ensaque e expedição, laboratório de controle de qualidade, área administrativa, vestiários e sanitários, e área externa.",
      "Incluir descrição do fluxo de produção: recebimento de MP → pesagem → dosagem → mistura → ensaque → expedição.",
      "O estabelecimento dispõe de layout que permite separar, por áreas e setores, o fluxo unidirecional de pessoas e produtos, de forma a evitar contaminação cruzada.",
    ],
  },
  {
    id: "pop01_fornecedores",
    numero: "5.1",
    titulo: "Qualificação de Fornecedores e Controle de MP (POP 01)",
    conteudo: [
      "A empresa mantém cadastro de fornecedores qualificados conforme critérios de avaliação que incluem: registro no MAPA/SIPEAGRO, certificados de análise, histórico de qualidade e cumprimento de especificações técnicas.",
      "As matérias-primas são recebidas e avaliadas quanto a: aspecto visual, odor, cor, umidade, temperatura, integridade da embalagem e presença de insetos ou corpos estranhos. A cada recebimento é verificada a nota fiscal e o certificado de análise.",
      "Para grãos, o padrão interno adotado é de no máximo 14% de umidade no recebimento. Se a MP for rejeitada, é proibida de ser descarregada e comunicado ao fornecedor.",
      "Para todas as matérias-primas recebidas são criados lotes internos conforme a Planilha de controle (PL POP 1.7). O operador utilizará sempre os lotes que chegaram primeiro, respeitando o FIFO/PEPS.",
    ],
  },
  {
    id: "pop02_limpeza",
    numero: "5.2",
    titulo: "Limpeza de Instalações, Equipamentos e Utensílios (POP 02)",
    conteudo: [
      "A limpeza de instalações, equipamentos e utensílios segue cronograma definido com frequência diária, semanal e mensal.",
      "Os métodos de higienização incluem: limpeza a seco (varrição, aspiração, soprador de folhas), limpeza úmida (água sob pressão, detergentes) e sanitização quando necessário.",
      "Cada área possui procedimento específico detalhando: responsável, frequência, partes a serem limpas, método de higienização, produtos e equipamentos utilizados, peças desmontáveis e EPIs necessários.",
      "O monitoramento é realizado pela conformidade da limpeza de 100% dos itens especificados em cada área, registrado por assinatura na planilha de Registro de Limpeza.",
      "Nunca o monitor pode ser o verificador e vice-versa.",
    ],
  },
  {
    id: "pop03_higiene",
    numero: "5.3",
    titulo: "Higiene e Saúde do Pessoal (POP 03)",
    conteudo: [
      "Os funcionários das áreas de manipulação recebem treinamento adequado na admissão e são continuamente treinados em relação à manipulação higiênica e higiene pessoal.",
      "Os funcionários utilizam o uniforme somente nas dependências da fábrica. São orientados a retirarem quaisquer objetos de adorno (anéis, alianças, pulseiras, relógios, brincos, cordões).",
      "Os funcionários devem estar sempre: uniformizados, com botinas limpas, cabelos cobertos por touca/boné, barbeados, com unhas aparadas e limpas, com mãos higienizadas.",
      "Funcionários enfermos são afastados do trabalho ou remanejados para trabalhos fora da área de produção. Colaboradores com ferimentos utilizam luvas de proteção.",
      "Procedimento de higiene das mãos: molhar o antebraço até o cotovelo, aplicar detergente bactericida, esfregar palma, dorso, antebraço, espaço entre dedos, polegar, unhas e pontas dos dedos, enxaguar e secar.",
      "As mãos são lavadas: ao entrar na seção de trabalho, após fumar, após recolher lixo, durante pausas, ao tocar o chão, após uso do banheiro, após tocar cabelo/nariz/corpo, depois de tossir ou espirrar.",
    ],
  },
  {
    id: "pop03_saude_aso",
    numero: "5.4",
    titulo: "Gestão de Saúde dos Manipuladores e ASO (POP 03)",
    conteudo: [
      "A empresa mantém programa de controle de saúde dos manipuladores conforme NR-7 (PCMSO) e POP 03 da IN 04/2007.",
      "─── EXAMES OBRIGATÓRIOS ───",
      "Todo colaborador da área de produção e manipulação deve possuir ASO (Atestado de Saúde Ocupacional) válido, emitido por médico do trabalho, contemplando os seguintes exames:",
      "• Admissional: realizado antes do início das atividades.",
      "• Periódico: anual para áreas de risco, bienal para demais áreas.",
      "• Demissional: realizado até a data de homologação da rescisão.",
      "• Retorno ao Trabalho: após afastamento ≥ 30 dias por doença ou acidente.",
      "─── EXAMES LABORATORIAIS ───",
      "• Coprocultura: pesquisa de Salmonella spp. e Shigella spp. — obrigatório para manipuladores.",
      "• Hemograma completo: avaliação geral de saúde.",
      "• VDRL: triagem para sífilis.",
      "• Parasitológico de fezes: detecção de parasitas intestinais.",
      "─── MONITORAMENTO DIÁRIO ───",
      "Supervisores devem observar diariamente os colaboradores quanto a: sintomas respiratórios (tosse, espirros), lesões cutâneas, diarreia, febre ou mal-estar. Colaboradores sintomáticos devem ser afastados da produção.",
      "─── CONTROLE DIGITAL ───",
      "O sistema FeedBPF permite o cadastro de cada colaborador com datas de ASO, vencimentos e alertas automáticos. Exames vencidos geram notificação para o RH e RT.",
    ],
  },
  {
    id: "pop04_agua",
    numero: "5.5",
    titulo: "Potabilidade da Água e Higienização dos Reservatórios (POP 04)",
    conteudo: [
      "A água utilizada na empresa é potável e monitorada conforme orientação do POP 04 da IN 04/2007 e Portaria GM/MS 888/2021.",
      "─── ORIGEM E DISTRIBUIÇÃO ───",
      "A origem da água pode ser de rede pública de abastecimento ou poço artesiano, com potabilidade controlada por laudos periódicos.",
      "A água chega por encanamento até as caixas d'água, que abastecem sanitários, bebedouros e áreas de produção.",
      "─── PARÂMETROS DE CONTROLE ───",
      "• Cloro Residual Livre: faixa aceitável de 0,2 a 2,0 mg/L, medido diariamente com kit DPD.",
      "• pH: faixa aceitável de 6,0 a 9,5.",
      "• Turbidez: máximo 5 NTU.",
      "• Coliformes Totais e E. coli: ausência em 100 mL (análise mensal/semestral).",
      "─── RESERVATÓRIOS ───",
      "Os reservatórios são higienizados semestralmente por empresa especializada, com emissão de certificado. A limpeza inclui: esvaziamento, escovação, enxágue, aplicação de hipoclorito 200 ppm por 30 minutos e novo enxágue.",
      "─── REGISTROS ───",
      "São mantidos registros diários de cloro e pH, laudos laboratoriais e certificados de higienização, arquivados por no mínimo 2 anos.",
    ],
  },
  {
    id: "pop05_contaminacao",
    numero: "5.6",
    titulo: "Prevenção de Contaminação Cruzada (POP 05)",
    conteudo: [
      "A empresa garante procedimentos para prevenir a contaminação cruzada de matéria-prima, produtos acabados e materiais de embalagem, não ocasionando contaminações de origem biológica, química ou física.",
      "São tomadas medidas para evitar contaminação por contato direto e indireto em todas as etapas do processo. As matérias-primas, embalagens e produto acabado são identificados e armazenados separados.",
      "O prédio e instalações da fábrica permitem separar, por áreas e setores, o fluxo unidirecional de pessoas e produtos, de forma a evitar contaminação cruzada.",
      "A empresa enfatiza através de treinamentos e conscientização dos colaboradores os riscos de contaminação cruzada. Todos os equipamentos e utensílios que entram em contato com matéria-prima são higienizados conforme POP 02.",
    ],
  },
  {
    id: "pop06_manutencao",
    numero: "5.7",
    titulo: "Manutenção e Calibração de Equipamentos (POP 06)",
    conteudo: [
      "A empresa é responsável em manter instrumentos de processo (balanças) conforme sua finalidade e, através da aferição, garantir a eficiência dos controles.",
      "A manutenção das instalações ocorre de forma corretiva (pequenos reparos) e preventiva. Durante manutenção corretiva, a área é isolada com fita de isolamento.",
      "Os equipamentos e utensílios são projetados de material não contaminante, inertes e de fácil desmontagem.",
      "A calibração das balanças é realizada por empresa terceirizada habilitada junto ao INMETRO. Cada balança calibrada possui laudo técnico informando suas especificações e condições atuais.",
      "Após realização dos serviços de manutenção é importante recolher ferramentas e peças substituídas para não comprometer a inocuidade dos produtos.",
    ],
  },
  {
    id: "pop07_pragas",
    numero: "5.8",
    titulo: "Controle Integrado de Pragas (POP 07)",
    conteudo: [
      "O programa de Controle Integrado de Pragas inclui medidas preventivas para impedir a invasão, instalação e proliferação de pragas, e aplicação de produtos químicos quando necessário.",
      "As aberturas entre parede e teto, portas e janelas são teladas para evitar presença de insetos alados e aves.",
      "A indústria monitora diariamente o controle integrado de pragas pela inspeção dos ambientes internos e externos.",
      "O controle integrado de pragas é realizado por empresa contratada, devidamente registrada na vigilância sanitária, com execução mensal.",
      "A empresa contratada possui: registro junto aos órgãos de Defesa Sanitária, responsável técnico, EPIs/EPCs específicos, ficha técnica de todos os produtos utilizados e treinamento atualizado.",
      "Para reforçar a vigilância contínua, é mantida a Planilha 7.3 — Observação Diária de Pragas, formulário físico afixado nas áreas críticas (produção, recebimento, depósito de MP, expedição e silos) onde os colaboradores registram a presença detectada de roedores, aves e insetos. O mesmo registro está disponível no Modo Tablet (Chão de Fábrica) para lançamento digital imediato no módulo /pragas.",
    ],
  },
  {
    id: "pop08_residuos",
    numero: "5.9",
    titulo: "Controle de Resíduos e Efluentes (POP 08)",
    conteudo: [
      "A empresa garante o manejo e destino dos resíduos e efluentes produzidos durante as operações, promovendo o atendimento às normas ambientais.",
      "Os resíduos são acondicionados, recolhidos, segregados e encaminhados para área externa onde aguardam destinação final. A frequência de retirada é de 1 vez por turno ou sempre que necessário.",
      "Após recolhimento, segregação e armazenamento, os resíduos são encaminhados para destinação final (coleta pública ou empresa especializada) sem causar risco ao produto ou ao meio ambiente.",
      "Os resíduos inerentes ao processo, embalagens e material descartável são depositados em área específica e removidos periodicamente como prevenção à proliferação de pragas.",
    ],
  },
  {
    id: "pop09_rastreabilidade",
    numero: "5.10",
    titulo: "Rastreabilidade e Recolhimento de Produtos — Recall (POP 09)",
    conteudo: [
      "A empresa garante a rastreabilidade dos produtos mediante a utilização de registros adequados para uma retirada ou recolhimento eficiente dos produtos.",
      "A rastreabilidade é realizada através do número do lote inserido na embalagem. Pelo lote e data de fabricação é possível localizar a ordem de produção.",
      "A rastreabilidade é assegurada no momento da fabricação, onde o operador insere na Ordem de Produção o lote de matéria-prima, núcleo e embalagens utilizados.",
      "Para realizar a rastreabilidade verifica-se: identificação da ração (número do lote) → identificação da Ordem de Produção → lotes das MP e embalagens.",
      "O procedimento de recall aplica-se em situações como: contaminação identificada após liberação dos produtos, ou prejuízo da imagem da empresa. A empresa possui equipe de recall e planos de ação para recolhimento ágil e seguro.",
      "Etapas do recall: Detectar → Acionar equipe → Comunicar → Rastrear produto no mercado → Isolar e recolher → Avaliar condições → Repor cliente → Tratar NC e realizar ações preventivas/corretivas.",
      "O sistema realiza testes de recall simulado com cronômetro, medindo a eficiência da equipe para rastrear um lote em até 4 horas, conforme Art. 28 do Decreto 12.031/2024.",
    ],
  },
  {
    id: "pop10_pac",
    numero: "5.11",
    titulo: "Programa de Autocontrole — PAC (POP 10)",
    conteudo: [
      "O Programa de Autocontrole (PAC) é o instrumento central de gestão da qualidade da empresa, integrando todos os 9 POPs obrigatórios e o Manual de BPF em um ciclo contínuo de verificação, auditoria e melhoria.",
      "─── ESTRUTURA DO PAC ───",
      "O PAC é composto por três pilares:",
      "1. CHECKLIST MENSAL DE AUTOCONTROLE (PL POP 10.1): Verificação mensal de conformidade de cada POP. Avalia se os registros estão completos, assinados e dentro do prazo de retenção.",
      "2. AUDITORIA INTERNA SEMESTRAL (PL POP 10.2): Auditoria documentada abrangendo todos os procedimentos operacionais. Gera relatório com não conformidades, ações corretivas e prazos.",
      "3. INDICADORES DE DESEMPENHO (PL POP 10.3): Monitoramento mensal de KPIs — % de conformidade dos POPs, NCs abertas/fechadas, reclamações de clientes, treinamentos realizados vs. programados, manutenções e calibrações em dia.",
      "─── PROCEDIMENTOS ───",
      "Realizar checklist mensal verificando a implementação de todos os POPs.",
      "Conduzir auditorias internas semestrais com auditor qualificado (que não seja o executor do processo auditado).",
      "Monitorar indicadores de desempenho mensalmente e apresentar resultados à direção.",
      "Revisar e atualizar POPs e Manual BPF anualmente ou quando houver alteração regulatória, mudança de processo ou NC crítica.",
      "Garantir que todos os registros estejam completos, assinados e arquivados pelo prazo de retenção legal (mínimo 2 anos para planilhas operacionais, 5 anos para manifestos, laudos e registros de recall).",
      "Preparar dossiê documental para verificações oficiais do SIF/DIPOA/MAPA.",
      "Tratar não conformidades de auditoria com ações corretivas e verificação de eficácia em 30/60/90 dias.",
      "─── FREQUÊNCIA DE AVALIAÇÃO ───",
      "• Mensal: Checklist de autocontrole e indicadores",
      "• Semestral: Auditoria interna completa",
      "• Anual: Revisão do Manual BPF e todos os POPs",
      "• A qualquer momento: Quando solicitado pelo SIF/MAPA ou após NC crítica/recall",
    ],
  },
  {
    id: "substancias_proibidas",
    numero: "5.12",
    titulo: "Controle de Substâncias Proibidas e Indesejáveis (IN 15/2009)",
    conteudo: [
      "Conforme a Instrução Normativa nº 15/2009 do MAPA, a empresa mantém programa de controle de substâncias proibidas, indesejáveis e contaminantes na alimentação animal.",
      "─── SUBSTÂNCIAS PROIBIDAS ───",
      "É terminantemente proibido o uso de:",
      "• Proteínas e gorduras de origem animal de ruminantes na alimentação de ruminantes (prevenção de EEB/BSE)",
      "• Cloranfenicol, nitrofuranos e seus derivados",
      "• Dietilestilbestrol (DES) e outros hormônios sintéticos proibidos",
      "• Avoparcina, olaquindox e carbadox",
      "─── SUBSTÂNCIAS COM LIMITES ───",
      "• Ionóforos (monensina, salinomicina, lasalocida): carry-over máximo < 1% para produtos sem medicamento",
      "• Medicamentos veterinários: carry-over máximo < 3% para espécies não-alvo",
      "• Micotoxinas — Aflatoxina: limite máximo ≤ 20 ppb (µg/kg) para rações",
      "• Metais pesados: conforme limites da legislação vigente",
      "─── CONTROLES IMPLEMENTADOS ───",
      "O sistema monitora continuamente:",
      "• Certificados de análise de cada lote de matéria-prima recebida",
      "• Testes de carry-over após limpeza de linha (flushing, HPLC, swab)",
      "• Sequenciamento de produção baseado na Matriz de Sensibilidade",
      "• Rastreabilidade de ingredientes de origem animal (alertas EEB automáticos)",
      "• Laudos laboratoriais de micotoxinas e resíduos químicos",
    ],
  },
  {
    id: "temperatura_armazenamento",
    numero: "5.13",
    titulo: "Controle de Temperatura e Umidade de Armazenamento",
    conteudo: [
      "O controle de temperatura e umidade nas áreas de armazenamento é essencial para preservar a qualidade das matérias-primas e produtos acabados, prevenindo a proliferação de fungos e formação de micotoxinas.",
      "─── PARÂMETROS DE CONTROLE ───",
      "• Silos de grãos: Temperatura máxima 30°C, Umidade relativa < 65%",
      "• Armazém de MP ensacadas: Temperatura ambiente monitorada, empilhamento sobre estrados",
      "• Armazém de PA: Temperatura ambiente monitorada, FIFO/PEPS rigoroso",
      "• Umidade de grãos armazenados: máximo 14% (milho e soja), verificação semanal (PL POP 1.5)",
      "─── PROCEDIMENTOS ───",
      "Monitoramento semanal de umidade de grãos em silos com medidor portátil.",
      "Inspeção visual de armazéns para detecção de condensação, infiltrações ou fermentação.",
      "Ventilação natural ou forçada de silos quando a temperatura ultrapassar 30°C.",
      "Registro de expurgo quando detectada infestação (PL POP 1.8).",
      "Grãos com umidade > 14% devem ser segregados e secos antes do uso na produção.",
    ],
  },
  {
    id: "retencao_amostras",
    numero: "5.14",
    titulo: "Retenção de Amostras de Contraprova",
    conteudo: [
      "A empresa mantém programa de retenção de amostras (contraprova) conforme exigido pela IN 04/2007 e pelo Decreto 12.031/2024.",
      "─── PROCEDIMENTO ───",
      "Para cada lote de produto acabado fabricado, é retida uma amostra representativa identificada com: nome do produto, número do lote, data de fabricação, data de validade e responsável pela coleta.",
      "As amostras são armazenadas em local seco, protegido da luz solar e identificado, pelo período equivalente ao prazo de validade do produto.",
      "─── FINALIDADE ───",
      "• Análise em caso de reclamação de cliente ou devolução",
      "• Verificação em caso de fiscalização do SIF/MAPA",
      "• Comprovação de conformidade em processos de recall",
      "• Análise comparativa em caso de suspeita de contaminação",
      "─── RASTREABILIDADE ───",
      "O sistema registra a localização física de cada amostra retida, vinculada ao lote de produção e à ordem de fabricação, permitindo localização em até 4 horas conforme requisito de recall.",
    ],
  },
  {
    id: "biosseguridade_visitantes",
    numero: "5.15",
    titulo: "Controle de Visitantes e Biosseguridade (IN 15/2009)",
    conteudo: [
      "O estabelecimento mantém procedimento de controle de acesso de visitantes conforme exigido pela IN 15/2009, visando a biosseguridade das instalações e prevenção de contaminações.",
      "─── PROCEDIMENTO DE ENTRADA ───",
      "Todo visitante deve:",
      "• Apresentar-se na portaria e registrar-se no livro de visitantes",
      "• Receber orientação de biosseguridade (normas de conduta, proibições, áreas restritas)",
      "• Utilizar EPIs fornecidos pela empresa: touca descartável, avental descartável, sapatos fechados ou propés",
      "• Ser acompanhado por funcionário responsável durante toda a visita",
      "─── REGISTRO ───",
      "São registrados: nome completo, empresa, documento de identidade, motivo da visita, áreas visitadas, horário de entrada e saída, acompanhante designado, confirmação de orientação e EPIs fornecidos.",
      "─── RESTRIÇÕES ───",
      "• Proibida a entrada de visitantes com sintomas de enfermidades transmissíveis",
      "• Proibido portar alimentos, bebidas, cigarros ou produtos não autorizados",
      "• Proibido fotografar ou filmar sem autorização prévia da direção",
      "• Visitantes não podem tocar em matérias-primas, produtos ou equipamentos sem autorização",
    ],
  },
  {
    id: "categorizacao_risco",
    numero: "6",
    titulo: "Categorização de Risco do Estabelecimento",
    conteudo: [
      "FUNDAMENTO LEGAL: A categorização de risco dos estabelecimentos fabricantes de produtos destinados à alimentação animal é regulamentada pelo Decreto nº 12.031/2024, que alterou o Decreto nº 6.296/2007 (RIISPOA Animal), e pela Instrução Normativa nº 17/2017 do MAPA, que estabelece o Regulamento Técnico de Boas Práticas de Fabricação.",
      "OBJETIVO: Classificar o estabelecimento em uma categoria de risco (Baixo, Médio, Alto ou Crítico) com base na avaliação de múltiplos fatores que influenciam a segurança do produto final, orientando a frequência de fiscalização e o nível de controles exigidos pelo MAPA.",
      "─── CRITÉRIOS DE CATEGORIZAÇÃO ───",
      "A categorização de risco considera os seguintes fatores principais, conforme legislação vigente:",
      "1. TIPO DE PRODUTO FABRICADO:",
      "• Rações medicamentosas e com aditivos medicamentosos → Risco ALTO a CRÍTICO",
      "• Suplementos e premixes com ionóforos/antibióticos → Risco ALTO",
      "• Rações completas para animais de produção → Risco MÉDIO a ALTO",
      "• Sal mineral e suplementos sem medicamentos → Risco BAIXO a MÉDIO",
      "• Produtos para animais de companhia (pet food) → Risco MÉDIO",
      "2. ESPÉCIES ATENDIDAS:",
      "• Fabricação multiespécie (ex: equinos + bovinos + aves) → AUMENTA o risco pela possibilidade de contaminação cruzada com substâncias restritivas (ex: monensina tóxica para equinos, ureia tóxica para monogástricos)",
      "• Fabricação para espécie única → risco MENOR por não haver incompatibilidades",
      "3. CAPACIDADE E VOLUME DE PRODUÇÃO:",
      "• Grandes volumes com múltiplas linhas → Risco MAIOR (maior chance de contaminação cruzada)",
      "• Produção artesanal/pequeno porte → Risco MENOR, mas requer os mesmos controles documentais",
      "4. HISTÓRICO DE CONFORMIDADE:",
      "• Histórico de NCs críticas, recalls ou interdições → ELEVA a categoria de risco",
      "• Histórico limpo com auditorias conformes → PODE REDUZIR a categoria na reavaliação",
      "5. USO DE SUBSTÂNCIAS CONTROLADAS:",
      "• Uso de ureia, ionóforos (monensina, salinomicina, lasalocida), antibióticos e coccidiostáticos → Risco ALTO",
      "• Uso de microminerais e vitaminas apenas → Risco BAIXO",
      "─── COMO CALCULAR O RISCO ───",
      "MÉTODO DE PONTUAÇÃO (baseado no Questionário de Autocontrole do MAPA):",
      "Etapa 1 — RESPONDER O QUESTIONÁRIO: Para cada pergunta de avaliação, atribuir uma das respostas:",
      "• SIM (Conforme) = recebe 100% do peso da pergunta",
      "• PARCIAL (Parcialmente conforme) = recebe 50% do peso",
      "• NÃO (Não conforme) = recebe 0% do peso",
      "• N/A (Não aplicável) = pergunta removida do cálculo",
      "Etapa 2 — CALCULAR A PONTUAÇÃO POR CATEGORIA: Somar os pontos obtidos e dividir pela pontuação máxima possível da categoria (excluindo N/A), multiplicando por 100 para obter o percentual de conformidade.",
      "Fórmula: % Conformidade = (Σ Pontos Obtidos / Σ Pontuação Máxima) × 100",
      "Etapa 3 — CLASSIFICAR O NÍVEL DE RISCO:",
      "• ≥ 80% de conformidade → Risco BAIXO (cor verde)",
      "• 50% a 79% de conformidade → Risco MÉDIO (cor amarela)",
      "• < 50% de conformidade → Risco ALTO (cor vermelha)",
      "─── CATEGORIAS DE AVALIAÇÃO ───",
      "O questionário abrange as seguintes categorias, alinhadas aos POPs e ao Decreto 12.031/2024:",
      "1. Infraestrutura e Instalações — Layout, piso, telas, iluminação",
      "2. Higiene e Sanitização — Cronograma, produtos, validação de limpeza",
      "3. Controle de Matérias-Primas — Qualificação de fornecedores, recebimento, substâncias proibidas",
      "4. Processo Produtivo — Sequenciamento, contaminação cruzada, tempos de mistura",
      "5. Controle de Pragas — Empresa contratada, mapa de iscas",
      "6. Treinamento de Pessoal — Capacitação BPF, cronograma",
      "7. Rastreabilidade — Rastreio bidirecional, procedimento de recall",
      "8. Equipamentos e Manutenção — Calibração, manutenção preventiva",
      "9. Documentação e Registros — POPs atualizados, registros completos",
      "10. Programa de Autocontrole (PAC) — Auditorias internas, indicadores",
      "─── AÇÕES CONFORME O RESULTADO ───",
      "RISCO BAIXO (≥80%): Manter os controles e documentação. Frequência de fiscalização do MAPA: reduzida. Foco em melhoria contínua.",
      "RISCO MÉDIO (50-79%): Elaborar plano de ação para itens não conformes com prazo definido. Priorizar as categorias com menor pontuação. Reavaliar em 90 dias.",
      "RISCO ALTO (<50%): Ação imediata obrigatória. Risco de interdição pelo SIF/MAPA. Elaborar plano de ação emergencial. Solicitar consultoria se necessário. Reavaliar em 30 dias.",
      "─── PERIODICIDADE DA AVALIAÇÃO ───",
      "A avaliação de risco deve ser realizada:",
      "• Semestralmente como rotina do PAC (Programa de Autocontrole)",
      "• Após mudanças significativas no processo (novos produtos, novos equipamentos, alteração de layout)",
      "• Após ocorrência de NC crítica ou recall",
      "• Quando solicitado pelo SIF/DIPOA/MAPA em fiscalização",
      "─── REFERÊNCIAS NORMATIVAS ───",
      "• Decreto nº 12.031/2024 — Altera o Decreto 6.296/2007 sobre inspeção e fiscalização de produtos para alimentação animal",
      "• Instrução Normativa nº 17/2017 — Regulamento Técnico de Boas Práticas de Fabricação",
      "• Instrução Normativa nº 04/2007 — Regulamento Técnico sobre condições higiênico-sanitárias",
      "• Instrução Normativa nº 15/2009 — Substâncias proibidas e indesejáveis na alimentação animal",
      "• Instrução Normativa nº 22/2009 — Rotulagem de produtos destinados à alimentação animal",
      "• Instrução Normativa nº 12/2004 — Cadastro de estabelecimentos e produtos no SIPEAGRO",
      "• NOTA: Utilize o módulo 'Matriz de Risco' > aba 'Questionário de Risco' do sistema para realizar a avaliação automatizada com cálculo de pontuação em tempo real.",
    ],
  },
  {
    id: "instrucoes_trabalho",
    numero: "7",
    titulo: "Instruções de Trabalho (ITs)",
    conteudo: [
      "As Instruções de Trabalho (ITs) são documentos operacionais subordinados aos POPs, que detalham o passo a passo para a execução de tarefas específicas no chão de fábrica. Cada IT está vinculada a um POP e serve como guia prático para os operadores.",
      "─── ESTRUTURA DE CADA IT ───",
      "• Objetivo: descrição clara da finalidade da instrução",
      "• Materiais: lista de materiais necessários para execução",
      "• EPIs obrigatórios: equipamentos de proteção individual requeridos",
      "• Passo a passo: sequência numerada de ações operacionais",
      "• Critérios de aceitação: parâmetros que definem se a execução é conforme",
      "• Frequência: periodicidade de execução (diária, semanal, mensal, etc.)",
      "• Registro vinculado: planilha de controle onde a execução é documentada",
      "─── ITs POR POP ───",
      "POP 01 — Qualificação de Fornecedores:",
      "• IT-01-01: Avaliação e Qualificação Inicial de Fornecedor",
      "• IT-01-02: Inspeção de Recebimento de Matéria-Prima a Granel",
      "• IT-01-03: Inspeção de Recebimento de Matéria-Prima Ensacada",
      "POP 02 — Limpeza de Instalações e Equipamentos:",
      "• IT-02-01: Limpeza a Seco de Áreas de Produção",
      "• IT-02-02: Limpeza Úmida e Sanitização",
      "• IT-02-03: Limpeza de Silos e Transportadores (IN 15/2009)",
      "POP 03 — Higiene e Saúde dos Colaboradores:",
      "• IT-03-01: Higiene Pessoal na Entrada da Fábrica",
      "• IT-03-02: Controle de Atestados de Saúde Ocupacional (ASO)",
      "POP 04 — Potabilidade da Água:",
      "• IT-04-01: Coleta de Amostras de Água para Análise",
      "• IT-04-02: Higienização de Reservatórios de Água",
      "POP 05 — Prevenção de Contaminação Cruzada:",
      "• IT-05-01: Sequenciamento de Produção e Flushing (IN 15/2009)",
      "• IT-05-02: Teste de Carry-Over (Arraste)",
      "POP 06 — Manutenção e Calibração:",
      "• IT-06-01: Manutenção Preventiva de Equipamentos Críticos",
      "• IT-06-02: Verificação Intermediária de Balanças",
      "POP 07 — Controle Integrado de Pragas:",
      "• IT-07-01: Monitoramento Semanal de Pragas",
      "• IT-07-02: Inspeção e Manutenção de Barreiras Físicas",
      "POP 08 — Controle de Resíduos e Efluentes:",
      "• IT-08-01: Segregação e Coleta de Resíduos",
      "• IT-08-02: Descarte de Produtos Não Conformes",
      "POP 09 — Rastreabilidade e Recall:",
      "• IT-09-01: Rastreabilidade de Lote de Produção",
      "• IT-09-02: Procedimento de Recall / Recolhimento",
      "POP 10 — Programa de Autocontrole (PAC):",
      "• IT-10-01: Auditoria Interna BPF",
      "• IT-10-02: Análise de Indicadores e Reunião de Resultados",
      "─── GESTÃO DAS ITs ───",
      "As ITs são revisadas anualmente junto com os POPs ou sempre que houver mudança no processo, equipamento ou legislação. Todas as ITs estão disponíveis para consulta no Guia dos POPs (/guia-pops) e como modelos na Biblioteca de Modelos (/modelos).",
      "Os operadores devem ser treinados nas ITs pertinentes às suas funções antes de executar as atividades. O registro do treinamento é feito no módulo de Treinamentos.",
      "─── REGISTRO DA EXECUÇÃO (DIÁRIO OPERACIONAL) ───",
      "Toda execução de POP/IT deve ser registrada no módulo Execução de ITs/POPs (/execucao-pops), que funciona como o diário de bordo digital da fábrica. Este registro é a evidência exigida pelo MAPA (IN 04/2007 Art. 4º e Decreto 12.031/2024) de que os procedimentos não ficam apenas no papel.",
      "• Painel de alertas: o sistema monitora a periodicidade de cada POP (POP-02 e POP-05 = 7 dias; POP-06 = 7 dias; POP-01, POP-03, POP-04, POP-07, POP-09 = 30 dias; POP-08 = 90 dias) e exibe em vermelho qualquer POP com execução atrasada.",
      "• Checklist específico por POP: ao registrar uma execução, o sistema carrega automaticamente o checklist do POP escolhido (12 itens triagem + ASO para POP-02; 15 itens limpeza + produto químico para POP-03; 11 itens potabilidade + laudo para POP-04; 16 itens higiene pessoal para POP-05; 8 itens vistoria veículo para POP-09).",
      "• Filtros de período: status, POP/IT, data início e data fim — permitindo gerar relatórios mensais, trimestrais ou por setor para auditoria.",
      "• Carimbo anti-fraude: cada execução exportada em PDF recebe selo SHA-256 + data/hora conforme MP 2.200-2/2001.",
      "Recomenda-se ao Responsável Técnico revisar este painel diariamente e não permitir que nenhum POP fique com status de atraso por mais de 48h.",
    ],
  },
  {
    id: "cadastro_inicial_documentos",
    numero: "7.1",
    titulo: "Checklist Inicial de Documentos para Ativação das Planilhas",
    conteudo: [
      "Antes de iniciar qualquer planilha física ou digital, o estabelecimento deve cadastrar no módulo Documentos os POPs e ITs com o mesmo código operacional utilizado na execução.",
      "O preenchimento padrão recomendado é: versão 01, data de revisão 2026-04-22, próxima revisão 2027-04-22, status Ativo e responsável 'Responsável Técnico / Qualidade'.",
      `Checklist-base: ${DOCUMENTOS_ATIVACAO_CHECKLIST.map((item) => `${item.codigo} — ${item.nome}`).join(" | ")}`,
      "Este cadastro inicial habilita os vínculos automáticos entre Documentos, Guia de POPs/ITs, planilhas físicas impressas, planilhas digitais e diário operacional.",
      "As impressões devem manter o carimbo de impressão e os PDFs/exportações devem preservar o carimbo anti-fraude SHA-256 para rastreabilidade documental.",
    ],
  },
  {
    id: "referencias_normativas",
    numero: "8",
    titulo: "Referências Normativas Aplicáveis",
    conteudo: [
      "Este Manual e os POPs associados foram elaborados em conformidade com a seguinte legislação vigente:",
      "─── LEGISLAÇÃO FEDERAL ───",
      "• Decreto nº 12.031/2024 — Inspeção e fiscalização de produtos destinados à alimentação animal",
      "• Instrução Normativa nº 04/2007 — Condições higiênico-sanitárias e BPF",
      "• Instrução Normativa nº 15/2009 — Substâncias proibidas, indesejáveis e contaminantes",
      "• Instrução Normativa nº 17/2017 — Regulamento Técnico de BPF (categorização de risco)",
      "• Instrução Normativa nº 22/2009 — Rotulagem de produtos para alimentação animal",
      "• Instrução Normativa nº 12/2004 — Cadastro de estabelecimentos e produtos (SIPEAGRO)",
      "• Instrução Normativa nº 30/2009 — Critérios para registro de rações e suplementos",
      "─── NORMAS TÉCNICAS ───",
      "• Portaria de Potabilidade da Água (MS) — Parâmetros microbiológicos e físico-químicos",
      "• NR-6, NR-7, NR-9 do MTE — Segurança e saúde ocupacional",
      "• INMETRO — Calibração de instrumentos de medição",
      "─── SISTEMA FEED BPF ───",
      "Todos os módulos do sistema estão alinhados com as exigências normativas acima, cobrindo:",
      "• 10 POPs obrigatórios com planilhas digitais (PL POP 1.1 a 10.3)",
      "• Checklists de liberação de linha e carry-over (IN 15/2009)",
      "• Rastreabilidade bidirecional e recall simulado (Decreto 12.031/2024)",
      "• Categorização de risco automatizada (IN 17/2017)",
      "• Sala do Auditor com 68 itens de fiscalização (Decreto 12.031/2024)",
      "• Controle de substâncias proibidas e alertas EEB (IN 15/2009)",
      "• Controle de visitantes e biosseguridade (IN 15/2009)",
      "• Gestão de ASOs com alertas automáticos de vencimento anual",
    ],
  },
];
