ALTER TABLE public.whatsapp_config
  ADD COLUMN IF NOT EXISTS last_known_status TEXT,
  ADD COLUMN IF NOT EXISTS last_status_check TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_status_change TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_alert_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS alert_email TEXT;

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;